title = "lexy: C++ parser combinator library"
baseURL = "https://lexy.foonathan.net/"
languageCode = "en-us"
copyright = "2020-2021"

ignoreFiles = [ "_reference" ]
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[markup.tableOfContents]
endLevel = 3
[markup.asciidocExt.attributes]
source-highlighter = "pygments"

[menu]
    [[menu.main]]
    name = "GitHub"
    weight = 4
    url = "https://github.com/foonathan/lexy"

