title = "lexy"
baseURL = "https://lexy.foonathan.net/"
languageCode = "en-us"
copyright = "2020-2021"

ignoreFiles = [ "_reference" ]
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[markup.tableOfContents]
endLevel = 3
[markup.asciidocExt.attributes]
source-highlighter = "pygments"

[params]
tagline = "C++ parser combinator library"
github = "https://github.com/foonathan/lexy"
github_src_prefix = "https://github.com/foonathan/lexy/blob/main"
github_edit_prefix = "https://github.com/foonathan/lexy/edit/main"

