name: Code Coverage

on: [push, pull_request]

jobs:
  code_coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: cmake -E make_directory build
    - name: Install ninja
      run: sudo apt-get -qq update && sudo apt-get install -y ninja-build

    - name: Configure
      working-directory: build/
      run: cmake -GNinja $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -DLEXY_BUILD_EXAMPLES=OFF -DLEXY_DISABLE_CONSTEXPR_TESTS=ON -DCMAKE_CXX_FLAGS="-O0 --coverage -DLEXY_FORCE_INLINE=inline" -DCMAKE_EXE_LINKER_FLAGS="--coverage"
    - name: Build
      working-directory: build/
      run: cmake --build .
    - name: Test
      working-directory: build/
      run: ctest -C Debug --output-on-failure

    - uses: codecov/codecov-action@v1

