name: Deploy Docs

on:
  push:
    branches: [main]

jobs:
  deploy_docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install asciidoctor
      run: sudo gem install asciidoctor rouge
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      working-directory: docs/
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/public/

