name: Deploy Docs

on:
  push:
    branches: [main]

jobs:
  deploy_docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install asciidoctor
      run: sudo gem install asciidoctor
    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DLEXY_BUILD_TESTS=OFF -DLEXY_BUILD_EXAMPLES=OFF
    - name: Build
      working-directory: build/
      run: cmake --build . --target lexy_docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html/

